{{- if .Values.mongo.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
{{- end }}
{{- if .Values.mongo5.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo5-persistent-storage-mongo5-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo5.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo5-persistent-storage-mongo5-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo5.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo5-persistent-storage-mongo5-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo5.resources.requests.storage }}
---
{{- end }}
{{- if .Values.solr.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}

---
{{- end }}
{{- if .Values.zk.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
{{- end }}
{{- if .Values.es.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-backup
  labels:
    component: elasticsearch
    role: es-pvc-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-0
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-1
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-2
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
{{- end }}
{{- if .Values.es7.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-backup-7
  labels:
    component: elasticsearch7
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-master-7-0
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-master-7-1
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-master-7-2
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-7-0
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-7-1
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-7-2
  labels:
    component: elasticsearch7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es7.resources.requests.storage }}
---
{{- end }}
{{- if .Values.customizer.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: customizernfsclaim
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.customizer.resources.requests.storage }}
---
{{- end }}
{{- if .Values.opensearch.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-backup-{{ .Values.opensearch.clusterName }}-backup
  labels:
    app.kubernetes.io/instance: opensearch-backup
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-master-{{ .Values.opensearch.clusterName }}-master-0
  labels:
    app.kubernetes.io/instance: opensearch-master
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-master-{{ .Values.opensearch.clusterName }}-master-1
  labels:
    app.kubernetes.io/instance: opensearch-master
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-master-{{ .Values.opensearch.clusterName }}-master-2
  labels:
    app.kubernetes.io/instance: opensearch-master
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-data-{{ .Values.opensearch.clusterName }}-data-0
  labels:
    app.kubernetes.io/instance: opensearch-data
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-data-{{ .Values.opensearch.clusterName }}-data-1
  labels:
    app.kubernetes.io/instance: opensearch-data
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-data-{{ .Values.opensearch.clusterName }}-data-2
  labels:
    app.kubernetes.io/instance: opensearch-data
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-client-{{ .Values.opensearch.clusterName }}-client-0
  labels:
    app.kubernetes.io/instance: opensearch-client
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-client-{{ .Values.opensearch.clusterName }}-client-1
  labels:
    app.kubernetes.io/instance: opensearch-client
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.opensearch.clusterName }}-client-{{ .Values.opensearch.clusterName }}-client-2
  labels:
    app.kubernetes.io/instance: opensearch-client
    app.kubernetes.io/name: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.opensearch.resources.requests.storage }}
---
{{- end }}
